name: ollama
description: "A modern and easy-to-use client for Ollama"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_chat_ui: ^1.6.13
  uuid: ^4.4.0
  animated_text_kit: ^4.2.2
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo512.png
