name: ollama_app
description: "A modern and easy-to-use client for Ollama"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_chat_ui: ^1.6.13
  uuid: ^4.4.0
  animated_text_kit: ^4.2.2
  image_picker: ^1.1.1
  visibility_detector: ^0.4.0+2
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.2.1
  dartx: ^1.2.0
  ollama_dart:
    git:
      url: https://github.com/davidmigloz/langchain_dart.git
      path: packages/ollama_dart
      ref: ce2ef30c9a9a0dfe8f3059988b7007c94c45b9bd
  smooth_page_indicator: ^1.1.0
  transparent_image: ^2.0.1
  simple_icons: ^10.1.3
  url_launcher: ^6.2.6
  restart_app: ^1.2.1
  flutter_markdown: ^0.7.1
  file_picker: ^8.0.3
  pick_or_save: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo512.png
    - assets/logo512error.png
    - assets/welcome/1.png
    - assets/welcome/2.png
    - assets/welcome/3.png
    - assets/welcome/1dark.png
    - assets/welcome/2dark.png
    - assets/welcome/3dark.png
